os: linux

services:
 - docker

archlinux:
  packages:
    - python
  script:
    - echo 'Hello World!'

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

notifications:
  irc:
    channels:
      - 'ircs://chat.freenode.net:7070/#archlinux-installer'
    template:
      - "[\x0313%{repository_name}\x0f] \x02\x0302%{result}\x0f \x0306%{branch}\x0f \x0314%{commit}\x0f \x0300%{author}\x0f: %{commit_subject}"
      - "Commit changes: \x0302%{compare_url}\x0f"
      - " Build details: \x0302%{build_url}\x0f"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false
